enum SampleData {
    static let sentences: [Sentence] = [
        .init(text: "The cat sat quietly on the warm windowsill", category: "Animals"),
        .init(text: "Dogs love playing fetch in the park", category: "Animals"),
        .init(text: "A kitten chased a ball of yarn across the floor", category: "Animals"),
        .init(text: "Dolphins are known for their intelligence and playful behavior", category: "Animals"),
        .init(text: "The eagle soared high above the mountain peaks", category: "Animals"),
        .init(text: "Goldfish swim in lazy circles around their bowl", category: "Animals"),
        .init(text: "Horses gallop freely across the open meadow", category: "Animals"),
        .init(text: "Fresh pasta tastes better than dried pasta from a box", category: "Food"),
        .init(text: "The chef prepared a delicious chocolate souffle", category: "Food"),
        .init(text: "Homemade bread fills the kitchen with a wonderful aroma", category: "Food"),
        .init(text: "Sushi requires fresh fish and perfectly seasoned rice", category: "Food"),
        .init(text: "A warm bowl of soup is perfect on a cold winter day", category: "Food"),
        .init(text: "Coffee beans from Ethiopia have a distinctive fruity flavor", category: "Food"),
        .init(text: "The farmers market sells organic vegetables every Saturday", category: "Food"),
        .init(text: "Machine learning models can recognize objects in photographs", category: "Technology"),
        .init(text: "Smartphones have become an essential part of daily life", category: "Technology"),
        .init(text: "Cloud computing allows businesses to scale their infrastructure", category: "Technology"),
        .init(text: "The new processor chip delivers twice the performance", category: "Technology"),
        .init(text: "Virtual reality headsets create immersive digital experiences", category: "Technology"),
        .init(text: "Open source software powers most of the internet", category: "Technology"),
        .init(text: "The sunset painted the sky in shades of orange and purple", category: "Nature"),
        .init(text: "Snow covered mountains glisten in the morning sunlight", category: "Nature"),
        .init(text: "A gentle rain began to fall on the quiet village", category: "Nature"),
        .init(text: "The forest floor was carpeted with fallen autumn leaves", category: "Nature"),
        .init(text: "Ocean waves crash against the rocky shoreline", category: "Nature"),
        .init(text: "Wildflowers bloom across the meadow in early spring", category: "Nature"),
        .init(text: "The marathon runner crossed the finish line with a new record", category: "Sports"),
        .init(text: "Basketball players practice free throws for hours every day", category: "Sports"),
        .init(text: "Swimming is one of the best full body exercises", category: "Sports"),
        .init(text: "The soccer match ended in a dramatic penalty shootout", category: "Sports"),
        .init(text: "Rock climbing requires both physical strength and mental focus", category: "Sports"),
        .init(text: "Yoga helps improve flexibility and reduce stress", category: "Sports"),
        .init(text: "The telescope revealed a new galaxy billions of light years away", category: "Science"),
        .init(text: "DNA contains the genetic instructions for all living organisms", category: "Science"),
        .init(text: "Quantum computers can solve certain problems exponentially faster", category: "Science"),
        .init(text: "Climate change is causing global temperatures to rise steadily", category: "Science"),
        .init(text: "Vaccines have eradicated several deadly diseases worldwide", category: "Science"),
        .init(text: "The human brain contains approximately one hundred billion neurons", category: "Science"),
        .init(text: "The ancient temples of Kyoto attract millions of visitors each year", category: "Travel"),
        .init(text: "Paris is famous for the Eiffel Tower and its charming cafes", category: "Travel"),
        .init(text: "Hiking through the Swiss Alps offers breathtaking panoramic views", category: "Travel"),
        .init(text: "The Caribbean beaches have crystal clear turquoise water", category: "Travel"),
        .init(text: "The orchestra performed Beethoven ninth symphony flawlessly", category: "Music"),
        .init(text: "Jazz music originated in New Orleans in the early twentieth century", category: "Music"),
        .init(text: "The painting captured the beauty of a rural countryside at dawn", category: "Arts"),
        .init(text: "Digital artists use tablets to create stunning illustrations", category: "Arts"),
    ]
}
